### ISSUE TITLE
Attention heatmaps in the paper

### ISSUE THREAD

**Issue by yf1019** [RenYurui/Global-Flow-Local-Attention#50]
Hi, this is a great work. But I'm wondering how to get this kind of attention heatmaps from your model, just as those shown in the paper?
![image](https://user-images.githubusercontent.com/44568791/88615117-d80aad80-d0c3-11ea-8087-c5fcfca99f98.png)

**Comment by RenYurui** [comment]
Our GFLA module can be seen as a sparse attention module, where the attention coefficients are calculated for the flowed positions.
In order to visualize the attention coefﬁcients, we ﬁrst calculate attention maps of all query locations in the red rectangle. Then the visualization heat map is calculated by summing the obtained attention maps.
Please refer to the [issue#24](https://github.com/RenYurui/Global-Flow-Local-Attention/issues/24) for more details.

**Comment by yf1019** [comment]
I get it. Thanks a lot for your help!
